#!/bin/bash
chmod u+x script

vertices=(5 10 15 20 25 30 35 40 45 50)

for vertex in vertices
do
	echo $vertex "\n" >> output.txt  

	for ((counter=0; counter<10; counter++))
	do
		./graphGen -$vertex | build/./ece650-prj -b >> output.txt
		echo "\n" >> output.txt
	done
done
